-- Top SaaS Cancellation Guides Seed
INSERT INTO public.cancellation_guides (service_name, cancellation_url, notice_period_days, steps, penalty_notes, is_annual_only)
VALUES 
('Slack', 'https://my.slack.com/admin/settings#billing', 0, '1. 관리자 메뉴 -> 설정 및 관리 -> 설정\n2. 과금 메뉴 선택\n3. 플랜 하단의 "플랜 변경" 또는 "워크스페이스 해지" 선택', '연간 결제 시 중도 해지해도 환불되지 않으며 남은 기간 동안 사용 가능합니다.', false),
('Notion', 'https://www.notion.so/billing', 0, '1. 설정 및 멤버 -> 청구\n2. 플랜 변경 또는 취소 선택', '워크스페이스 삭제와 요금제 해지는 별개입니다.', false),
('Google Workspace', 'https://admin.google.com/ac/billing/subscriptions', 30, '1. 관리 콘솔 -> 결제 -> 구독\n2. 해당 구독 선택 -> 구독 취소 선택', '연간 요금제의 경우 남은 기간에 대한 위약금이 발생할 수 있습니다.', true),
('AWS', 'https://console.aws.amazon.com/billing/home#/account', 0, '1. Billing Dashboard -> Account\n2. 하단의 "Close Account" 선택 또는 각 리소스별 중지', '리소스 삭제를 잊으면 계정 폐쇄 후에도 추가 과금이 발생할 수 있습니다.', false),
('ChatGPT Pro', 'https://chat.openai.com/#settings/Billing', 0, '1. 설정 -> My plan -> Manage my subscription\n2. 취소 선택', '해지 즉시 혜택이 사라지지 않고 결제 주기 끝까지 유지됩니다.', false),
('Claude Max', 'https://claude.ai/settings/billing', 0, '1. Settings -> Billing\n2. Manage Subscription -> Cancel Plan', '구독 기간 종료 시까지 유료 기능을 계속 사용할 수 있습니다.', false),
('Gemini Pro', 'https://one.google.com/subscriptions', 0, '1. Google One -> 설정\n2. 멤버십 관리 -> 멤버십 취소', 'Google One 구독과 연동되어 있으면 함께 확인해야 합니다.', false),
('Perplexity Pro', 'https://www.perplexity.ai/settings/account', 0, '1. Settings -> Subscription\n2. Manage plan -> Cancel', '결제 플랫폼(웹/앱스토어)에 따라 취소 경로가 다를 수 있습니다.', false),
('Midjourney', 'https://www.midjourney.com/account/', 0, '1. Account -> Manage Subscription\n2. Cancel Plan 선택', '할인 연간 플랜은 중도 환불이 제한될 수 있습니다.', true),
('Runway', 'https://app.runwayml.com/account/billing', 0, '1. Account settings -> Billing\n2. Manage subscription -> Cancel', '워크스페이스 단위 결제인지 개인 결제인지 확인이 필요합니다.', false),
('Cursor', 'https://www.cursor.com/settings/billing', 0, '1. Settings -> Billing\n2. Cancel subscription', '팀 플랜은 오너 권한이 필요할 수 있습니다.', false),
('GitHub Copilot', 'https://github.com/settings/copilot', 0, '1. GitHub Settings -> Copilot\n2. Manage subscription -> Cancel', '조직 단위 할당 중인 라이선스는 별도 회수가 필요합니다.', false),
('Figma', 'https://www.figma.com/settings/billing', 0, '1. Admin Console -> Billing\n2. 하단의 "Cancel subscription" 선택', '팀이나 프로젝트 삭제로는 해지되지 않습니다.', false),
('Canva', 'https://www.canva.com/settings/billing', 0, '1. Account settings -> Billing & plans\n2. Cancel plan 선택', '팀 멤버를 삭제해도 플랜은 유지될 수 있습니다.', false),
('Zoom', 'https://zoom.us/billing', 0, '1. 계정 관리 -> 청구 -> 유효한 플랜\n2. 구독 취소 선택', '자동 갱신일 최소 24시간 전에 취소해야 합니다.', false),
('Microsoft 365', 'https://admin.microsoft.com/Adminportal/Home#/subscriptions', 0, '1. Admin center -> Billing -> Your products\n2. 구독 선택 후 취소', '연간 약정은 위약금이 발생할 수 있습니다.', true),
('Asana', 'https://app.asana.com/admin/billing', 0, '1. Admin Console -> Billing\n2. Manage plan -> Cancel', '워크스페이스가 여러 개면 각각 확인해야 합니다.', false),
('Trello', 'https://trello.com/billing', 0, '1. Workspace settings -> Billing\n2. Change plan -> Cancel', '유료 Power-Up 사용 여부를 먼저 확인하세요.', false),
('Jira', 'https://admin.atlassian.com/billing', 0, '1. Atlassian admin -> Billing\n2. 제품별 플랜 취소', 'Jira/Confluence가 같은 결제 계정일 수 있습니다.', false),
('Confluence', 'https://admin.atlassian.com/billing', 0, '1. Atlassian admin -> Billing\n2. 제품별 플랜 취소', '같은 사이트 내 다른 Atlassian 제품 영향 여부를 확인하세요.', false),
('Linear', 'https://linear.app/settings/billing', 0, '1. Settings -> Billing\n2. Manage subscription -> Cancel', '오너 권한이 필요합니다.', false),
('Airtable', 'https://airtable.com/account', 0, '1. Workspace settings -> Billing\n2. Downgrade/Cancel', '워크스페이스별 과금이라 중복 결제가 잦습니다.', false),
('Zapier', 'https://zapier.com/app/billing/manage', 0, '1. Billing -> Plan\n2. Change plan -> Free', '태스크 초과 과금 내역을 같이 점검하세요.', false),
('Make', 'https://www.make.com/en/pricing', 0, '1. Organization settings -> Billing\n2. Cancel subscription', '추가 작업량 초과 요금 여부를 확인하세요.', false),
('HubSpot', 'https://app.hubspot.com/account-and-billing', 30, '1. Account & Billing -> Products\n2. Remove products 또는 downgrade', '약정 기간 상품은 즉시 해지가 제한될 수 있습니다.', true),
('Salesforce', 'https://help.salesforce.com/', 30, '1. 계약 담당 CSM 또는 지원 채널로 해지 요청\n2. 계약 만기 이전 통보', '계약 기반 해지가 많아 사전 통보 기한 확인이 필요합니다.', true),
('Miro', 'https://miro.com/app/settings/company/billing/', 0, '1. Company settings -> Billing\n2. Cancel subscription', '좌석 기반 과금이라 미사용 계정 정리가 먼저 필요합니다.', false),
('Loom', 'https://www.loom.com/settings/workspace/billing', 0, '1. Workspace settings -> Billing\n2. Manage plan -> Cancel', '워크스페이스 오너만 취소할 수 있습니다.', false),
('Dropbox', 'https://www.dropbox.com/account/plan', 0, '1. Account -> Plan\n2. Manage plan -> Cancel', '무료 전환 시 용량 초과 데이터는 동기화 제한이 생길 수 있습니다.', false),
('Adobe', 'https://account.adobe.com/plans', 14, '1. 내 플랜 -> 플랜 관리 -> 플랜 취소\n2. 취소 사유 선택 및 확인', '최초 결제 후 14일 이후 해지 시 남은 기간 요금의 50%가 위약금으로 부과될 수 있습니다.', true)
ON CONFLICT (service_name) DO UPDATE 
SET cancellation_url = EXCLUDED.cancellation_url,
    steps = EXCLUDED.steps,
    penalty_notes = EXCLUDED.penalty_notes;
